# Generated by Django 5.2.4 on 2025-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=40, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/branch/')),
                ('seats', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ourfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/faculty')),
                ('qualification', models.CharField(max_length=40, null=True)),
                ('experience', models.CharField(max_length=40, null=True)),
                ('fposts', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ourplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/placement')),
                ('psession', models.CharField(max_length=20, null=True)),
                ('company', models.CharField(max_length=40, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
